-- YouzAI Supabase schema
-- Jalankan di Supabase SQL Editor

create extension if not exists pgcrypto;

create table if not exists public.premium_users (
  user_key text primary key,
  plan_name text not null default 'premium',
  status text not null default 'active',
  started_at timestamptz,
  expires_at timestamptz,
  confirmed_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_daily (
  user_key text not null,
  usage_date date not null,
  chat_count integer not null default 0,
  image_count integer not null default 0,
  primary key (user_key, usage_date)
);

create table if not exists public.chat_history (
  id text primary key,
  user_key text not null,
  conversation_id text,
  model text,
  action text,
  user_message text,
  assistant_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  user_key text primary key,
  id text,
  name text,
  email text,
  picture text,
  updated_at timestamptz not null default now()
);

create table if not exists public.premium_requests (
  id bigint generated by default as identity primary key,
  user_key text not null,
  name text,
  email text,
  method text not null default 'qris',
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists idx_usage_daily_user_date on public.usage_daily(user_key, usage_date);
create index if not exists idx_chat_history_user_created on public.chat_history(user_key, created_at desc);
create index if not exists idx_premium_requests_user_created on public.premium_requests(user_key, created_at desc);
